kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: surrounding-system-web-app
  namespace: surrounding-dev-axa-magi-id
  uid: fd50555e-de41-473b-b82b-964775339a07
  resourceVersion: '1923029280'
  generation: 33
  creationTimestamp: '2025-11-18T07:44:02Z'
  labels:
    app: surrounding-system-web-app
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2026-01-06T07:48:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:failedBuildsHistoryLimit': {}
          'f:output':
            'f:to': {}
          'f:resources':
            'f:limits':
              .: {}
              'f:cpu': {}
              'f:memory': {}
            'f:requests':
              .: {}
              'f:cpu': {}
              'f:memory': {}
          'f:runPolicy': {}
          'f:source':
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:sourceSecret': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
              'f:env': {}
            'f:type': {}
          'f:successfulBuildsHistoryLimit': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2026-01-06T07:58:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'surrounding-system-web-app:latest'
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: DOCKER_BUILDKIT
          value: '1'
        - name: DOTNET_CLI_TELEMETRY_OPTOUT
          value: '1'
        - name: secrets.GITHUB_TOKEN
          value: 
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@github.axa.com:aii/surrounding-system-web-app.git'
      ref: development
    sourceSecret:
      name: git-ssh-surrounding-system
  triggers:
    - type: GitHub
      github:
        secret: your-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 28
