apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sonar
  namespace: sonarqube-developer-prod-axa-magi-id
spec:
  to:
    kind: Service
    name: sonar
  port:
    targetPort: 9000
  tls:
    termination: edge
