apiVersion: v1
kind: Service
metadata:
  name: sonar
  namespace: sonarqube-developer-prod-axa-magi-id
spec:
  selector:
    name: sonar
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
